/**
 * Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/*!
 * \file batch_norm_v3_def.cpp
 * \brief
 */

#include "register/op_def_registry.h"
namespace ops {
class BatchNormV3 : public OpDef {
public:
    explicit BatchNormV3(const char *name) : OpDef(name)
    {
        this->Input("x")
            .ParamType(REQUIRED)
            .DataType({ge::DT_FLOAT,
                ge::DT_FLOAT16,
                ge::DT_BF16,
                ge::DT_FLOAT,
                ge::DT_FLOAT16,
                ge::DT_BF16,
                ge::DT_FLOAT16,
                ge::DT_BF16,
                ge::DT_FLOAT16,
                ge::DT_BF16})
            .Format({ge::FORMAT_NCHW,
                ge::FORMAT_NCHW,
                ge::FORMAT_NCHW,
                ge::FORMAT_NCDHW,
                ge::FORMAT_NCDHW,
                ge::FORMAT_NCDHW,
                ge::FORMAT_NCHW,
                ge::FORMAT_NCHW,
                ge::FORMAT_NCDHW,
                ge::FORMAT_NCDHW})
            .UnknownShapeFormat({ge::FORMAT_NCHW,
                ge::FORMAT_NCHW,
                ge::FORMAT_NCHW,
                ge::FORMAT_NCDHW,
                ge::FORMAT_NCDHW,
                ge::FORMAT_NCDHW,
                ge::FORMAT_NCHW,
                ge::FORMAT_NCHW,
                ge::FORMAT_NCDHW,
                ge::FORMAT_NCDHW});

        this->Input("weight")
            .ParamType(REQUIRED)
            .DataType({ge::DT_FLOAT,
                ge::DT_FLOAT16,
                ge::DT_BF16,
                ge::DT_FLOAT,
                ge::DT_FLOAT16,
                ge::DT_BF16,
                ge::DT_FLOAT,
                ge::DT_FLOAT,
                ge::DT_FLOAT,
                ge::DT_FLOAT})
            .Format({ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND})
            .UnknownShapeFormat({ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND});

        this->Input("bias")
            .ParamType(REQUIRED)
            .DataType({ge::DT_FLOAT,
                ge::DT_FLOAT16,
                ge::DT_BF16,
                ge::DT_FLOAT,
                ge::DT_FLOAT16,
                ge::DT_BF16,
                ge::DT_FLOAT,
                ge::DT_FLOAT,
                ge::DT_FLOAT,
                ge::DT_FLOAT})
            .Format({ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND})
            .UnknownShapeFormat({ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND});

        this->Input("running_mean")
            .ParamType(REQUIRED)
            .DataType({ge::DT_FLOAT,
                ge::DT_FLOAT,
                ge::DT_FLOAT,
                ge::DT_FLOAT,
                ge::DT_FLOAT,
                ge::DT_FLOAT,
                ge::DT_FLOAT,
                ge::DT_FLOAT,
                ge::DT_FLOAT,
                ge::DT_FLOAT})
            .Format({ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND})
            .UnknownShapeFormat({ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND});

        this->Input("running_var")
            .ParamType(REQUIRED)
            .DataType({ge::DT_FLOAT,
                ge::DT_FLOAT,
                ge::DT_FLOAT,
                ge::DT_FLOAT,
                ge::DT_FLOAT,
                ge::DT_FLOAT,
                ge::DT_FLOAT,
                ge::DT_FLOAT,
                ge::DT_FLOAT,
                ge::DT_FLOAT})
            .Format({ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND})
            .UnknownShapeFormat({ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND});

        this->Output("y")
            .ParamType(REQUIRED)
            .DataType({ge::DT_FLOAT,
                ge::DT_FLOAT16,
                ge::DT_BF16,
                ge::DT_FLOAT,
                ge::DT_FLOAT16,
                ge::DT_BF16,
                ge::DT_FLOAT16,
                ge::DT_BF16,
                ge::DT_FLOAT16,
                ge::DT_BF16})
            .Format({ge::FORMAT_NCHW,
                ge::FORMAT_NCHW,
                ge::FORMAT_NCHW,
                ge::FORMAT_NCDHW,
                ge::FORMAT_NCDHW,
                ge::FORMAT_NCDHW,
                ge::FORMAT_NCHW,
                ge::FORMAT_NCHW,
                ge::FORMAT_NCDHW,
                ge::FORMAT_NCDHW})
            .UnknownShapeFormat({ge::FORMAT_NCHW,
                ge::FORMAT_NCHW,
                ge::FORMAT_NCHW,
                ge::FORMAT_NCDHW,
                ge::FORMAT_NCDHW,
                ge::FORMAT_NCDHW,
                ge::FORMAT_NCHW,
                ge::FORMAT_NCHW,
                ge::FORMAT_NCDHW,
                ge::FORMAT_NCDHW});

        this->Output("running_mean")
            .ParamType(REQUIRED)
            .DataType({ge::DT_FLOAT,
                ge::DT_FLOAT,
                ge::DT_FLOAT,
                ge::DT_FLOAT,
                ge::DT_FLOAT,
                ge::DT_FLOAT,
                ge::DT_FLOAT,
                ge::DT_FLOAT,
                ge::DT_FLOAT,
                ge::DT_FLOAT})
            .Format({ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND})
            .UnknownShapeFormat({ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND});

        this->Output("running_var")
            .ParamType(REQUIRED)
            .DataType({ge::DT_FLOAT,
                ge::DT_FLOAT,
                ge::DT_FLOAT,
                ge::DT_FLOAT,
                ge::DT_FLOAT,
                ge::DT_FLOAT,
                ge::DT_FLOAT,
                ge::DT_FLOAT,
                ge::DT_FLOAT,
                ge::DT_FLOAT})
            .Format({ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND})
            .UnknownShapeFormat({ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND});

        this->Output("save_mean")
            .ParamType(REQUIRED)
            .DataType({ge::DT_FLOAT,
                ge::DT_FLOAT,
                ge::DT_FLOAT,
                ge::DT_FLOAT,
                ge::DT_FLOAT,
                ge::DT_FLOAT,
                ge::DT_FLOAT,
                ge::DT_FLOAT,
                ge::DT_FLOAT,
                ge::DT_FLOAT})
            .Format({ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND})
            .UnknownShapeFormat({ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND});

        this->Output("save_rstd")
            .ParamType(REQUIRED)
            .DataType({ge::DT_FLOAT,
                ge::DT_FLOAT,
                ge::DT_FLOAT,
                ge::DT_FLOAT,
                ge::DT_FLOAT,
                ge::DT_FLOAT,
                ge::DT_FLOAT,
                ge::DT_FLOAT,
                ge::DT_FLOAT,
                ge::DT_FLOAT})
            .Format({ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND})
            .UnknownShapeFormat({ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND,
                ge::FORMAT_ND});

        this->Attr("epsilon").AttrType(OPTIONAL).Float(1e-5);
        this->Attr("momentum").AttrType(OPTIONAL).Float(0.1);
        this->Attr("is_training").AttrType(OPTIONAL).Bool(true);
        this->AICore().AddConfig("ascend910b");
        this->AICore().AddConfig("ascend910_93");
    }
};

OP_ADD(BatchNormV3);
}  // namespace ops